'Phoenix : A Massive RPG 
'ICS3U ISU 
'ISU by : Harsh Mistry 
'Powered by the Qian Engine : A Infinity Computing Production 
'Map Values generated by Qian Map Editor : Made by Harsh Mistry 

Module modMap2
    'Load Map 2 Values 
    Public Sub MapLoad2(ByVal map As Array)

        'Erase Original Map 
        For count As Integer = 0 To 100
            For count2 As Integer = 0 To 100
                For layer As Integer = 0 To 10
                    map(count, count2, layer) = 0 'Set all cells to  = 0 
                    map(count, count2, 0) = 3 'Make Background Black 
                Next
            Next
        Next

        



        'Background tile values (X,Y,0) 

        'Stone Block area (72,75) - (77,80) 
        For count As Integer = 72 To 77
            For count2 As Integer = 75 To 80
                map(count, count2, 0) = 1
            Next
        Next

        'Stone block area (47,47) -(51,51) 
        For count As Integer = 47 To 51
            For count2 As Integer = 47 To 51
                map(count, count2, 0) = 1
            Next
        Next

        'Stone Block Area (44,19) - (48,23) 
        For count As Integer = 44 To 48
            For count2 As Integer = 19 To 23
                map(count, count2, 0) = 1
            Next
        Next


        'Foreground Tiles (X,Y,2) 

        'Glass area (73,76) - (76,79) 
        For count As Integer = 73 To 76
            For count2 As Integer = 76 To 79
                map(count, count2, 2) = 2
            Next
        Next

        'Glass Area (48,48) - (50,50) 
        For count As Integer = 48 To 50
            For count2 As Integer = 48 To 50
                map(count, count2, 2) = 2
            Next
        Next

        'glass Area (45,20) - (47,22) 
        For count As Integer = 45 To 47
            For count2 As Integer = 20 To 22
                map(count, count2, 2) = 2
            Next
        Next
        

        'Glass Exits
        map(74, 79, 2) = 4
        map(49, 50, 2) = 4
        map(45, 22, 2) = 4

        'Foreground Tiles 2 (X,Y,5) 

        map(73, 75, 6) = 11
        map(73, 74, 6) = 10
        map(76, 75, 6) = 11
        map(76, 74, 6) = 10



        'NPC Tile Values (X,Y,3) 
        map(74, 76, 3) = 20 'The Lord
        map(49, 48, 3) = 20 'The Master
        map(45, 20, 3) = 20 'The Leader

        'Interact Tile Values (X,Y,4)
        map(74, 77, 4) = 28 'Battle with the lord
        map(74, 79, 4) = 29 'Exit 
        map(49, 50, 4) = 29 'Exit 2
        map(49, 49, 4) = 31 'Battle with the Master
        map(45, 22, 4) = 29 'Exit 3
        map(45, 21, 4) = 34 'Battle with the Leader


    End Sub


    'Update Interact Values for Map 2 
    Public Sub UpdateInteract(ByRef map As Array)

        'Set Interact Values only if map is not 1
        If modSaveData.map <> 1 Then
            map(74, 77, 4) = 28 'Battle with the lord
            map(74, 79, 4) = 29 'Exit 
            map(49, 50, 4) = 29 'Exit 2
            map(49, 49, 4) = 31 'Battle with the Master
            map(45, 22, 4) = 29 'Exit 3
            map(45, 21, 4) = 34 'Battle with the Leader

        End If
    End Sub

End Module
