'Phoenix : A Massive RPG 
'ICS3U ISU 
'ISU by : Harsh Mistry 
'Powered by the Qian Engine : A Infinity Computing Production 
'Map Values generated by Qian Map Editor : Made by Harsh Mistry 

Module modMap1
    'Set Values for Map 1
    Public Sub loadMap1(ByVal map As Array)


        'Set background Tile Values (X,Y,0)
        map(21, 21, 0) = 1
        map(21, 22, 0) = 1
        map(21, 23, 0) = 1
        map(22, 21, 0) = 1
        map(23, 21, 0) = 1
        map(23, 22, 0) = 1
        map(23, 23, 0) = 1

        'Grass Area (33,28) - (45,53)
        For count As Integer = 33 To 45
            For count2 As Integer = 28 To 35
                map(count, count2, 0) = 2
            Next
        Next

        'stone block area around spawn point 
        map(30, 25, 0) = 1
        map(30, 26, 0) = 1
        map(20, 25, 0) = 1
        map(20, 26, 0) = 1

        'Stone Block Area (32,27) - (46,36)
        For count As Integer = 32 To 46
            If count <> 27 Then 'Make sure it des not draw over entrance
                map(count, 27, 0) = 1
            End If
        Next

        For count As Integer = 27 To 36
            map(32, count, 0) = 1
        Next


        For count As Integer = 27 To 36
            map(46, count, 0) = 1
        Next

        For count As Integer = 32 To 46
            map(count, 36, 0) = 1
        Next

        'Stone Block area (24,37) - (26,43)
        For count As Integer = 38 To 43
            map(24, count, 0) = 1
            map(26, count, 0) = 1
        Next

        'Stone Block area (50,58) - (62,71)
        For count As Integer = 50 To 62
            For count2 As Integer = 58 To 71
                map(count, count2, 0) = 1
            Next
        Next


        'Stone Block Area (41,52) - (51,52) 
        For count As Integer = 41 To 55
            map(count, 52, 0) = 1
        Next

        'Stone Block area (30,28) - (30,37)
        For count As Integer = 28 To 37
            map(30, count, 0) = 1
        Next

        'Stone Block area (20,28) - (20,37)
        For count As Integer = 28 To 37
            map(20, count, 0) = 1
        Next

        'Stone Block Area (24,21) - (48,21)
        For count As Integer = 24 To 49
            map(count, 21, 0) = 1
        Next

        'Stone Block Area (24,65) - (26,73) 
        For count As Integer = 24 To 26
            For count2 As Integer = 65 To 73
                map(count, count2, 0) = 1
            Next
        Next

        'Stone Block Area (41,50) - (55,50)
        For count As Integer = 41 To 55

            map(count, 50, 0) = 1

        Next


        'Red Carpet Area (20,44) - (40,51)
        For count As Integer = 20 To 40
            For count2 As Integer = 44 To 51
                map(count, count2, 0) = 10
            Next
        Next

        'Red Carpet Yellow top Border(20, 44) - (40,44)
        For count As Integer = 20 To 40
            map(count, 44, 0) = 8
        Next

        'Red Carpet Yellow Bottom Border (20,51) - (40-51)
        For count As Integer = 20 To 40
            map(count, 51, 0) = 9
        Next

        'Red Carpet Yellow left Border (20,44) - (20,51) 
        For count As Integer = 44 To 51
            map(20, count, 0) = 11
        Next

        'Red Carpet Yellow right Border (40,44) - (40,51) 
        For count As Integer = 44 To 51
            map(40, count, 0) = 12
        Next


        'Stone Block Area (19,44) - (19,51) 
        For count As Integer = 44 To 51
            map(19, count, 0) = 1
        Next

        'Stone Block Area (41,44) - (41,51) 
        For count As Integer = 44 To 51
            map(41, count, 0) = 1
        Next

        'Stone Block Area (19,52) - (41,52) 
        For count As Integer = 19 To 41
            map(count, 52, 0) = 1
        Next

        'Stone Block Area (19,43) - (41,43) 
        For count As Integer = 19 To 41
            map(count, 43, 0) = 1
        Next

        'Stone Block Area (24,52) - (26,58) 
        For count As Integer = 52 To 58
            map(24, count, 0) = 1
            map(26, count, 0) = 1
        Next

        'Stone block area (20,58) - (45,68)
        For count As Integer = 19 To 43
            For count2 As Integer = 58 To 65
                map(count, count2, 0) = 1
            Next
        Next

        'Stone Block area (43,63) - (50,65) 
        For count As Integer = 43 To 50
            For count2 As Integer = 63 To 65
                map(count, count2, 0) = 1
            Next
        Next

        'Stone Block area (19,73) - (40,85) 
        For count As Integer = 19 To 40
            For count2 As Integer = 73 To 85
                map(count, count2, 0) = 1
            Next
        Next

        'Stone Block area (40,78) - (64,80)
        For count As Integer = 40 To 64
            For count2 As Integer = 78 To 80
                map(count, count2, 0) = 1
            Next
        Next

        'Stone Block area (64,68) - (83,86)
        For count As Integer = 64 To 83
            For count2 As Integer = 68 To 86
                map(count, count2, 0) = 1
            Next
        Next



        'Stone block Area to maintain 2.5D impression 
        map(40, 26, 0) = 1
        map(40, 25, 0) = 1
        map(38, 26, 0) = 1
        map(38, 25, 0) = 1
        map(38, 24, 0) = 1
        map(40, 24, 0) = 1
        map(50, 21, 0) = 1
        map(50, 22, 0) = 1
        map(50, 23, 0) = 1
        map(20, 44, 0) = 4
        map(20, 51, 0) = 5
        map(40, 44, 0) = 6
        map(40, 51, 0) = 7
        map(41, 51, 0) = 0
        map(55, 51, 0) = 1
        map(48, 50, 0) = 0
        map(49, 50, 0) = 0
        map(49, 49, 0) = 1
        map(48, 49, 0) = 1
        map(25, 65, 0) = 0
        map(43, 64, 0) = 0
        map(40, 79, 0) = 0
        map(46, 21, 0) = 0
        map(46, 20, 2) = 1
        map(45, 21, 2) = 1


        'Make borders solid
        For count As Integer = 0 To 100
            'East Border
            map(91, count, 1) = 1
            map(91, count, 0) = 1

            'West Border
            map(10, count, 1) = 1
            map(10, count, 0) = 1

            'North Border
            map(count, 10, 1) = 1
            map(count, 10, 0) = 1

            'South Border
            map(count, 91, 1) = 1
            map(count, 91, 0) = 1
        Next

        'Fix overdraw
        For count As Integer = 0 To 100
            'East Border
            map(92, count, 0) = 3
            map(93, count, 0) = 3
            map(94, count, 0) = 3
            map(95, count, 0) = 3
            map(96, count, 0) = 3
            map(97, count, 0) = 3
            map(98, count, 0) = 3
            map(99, count, 0) = 3
            map(100, count, 0) = 3

            'West Border
            map(9, count, 0) = 3
            map(8, count, 0) = 3
            map(7, count, 0) = 3
            map(6, count, 0) = 3
            map(5, count, 0) = 3
            map(4, count, 0) = 3
            map(3, count, 0) = 3
            map(2, count, 0) = 3
            map(1, count, 0) = 3
            map(0, count, 0) = 3

            'South Border 
            map(count, 92, 0) = 3
            map(count, 93, 0) = 3
            map(count, 94, 0) = 3
            map(count, 95, 0) = 3
            map(count, 96, 0) = 3
            map(count, 97, 0) = 3
            map(count, 98, 0) = 3
            map(count, 99, 0) = 3
            map(count, 100, 0) = 3

            'North Border
            map(count, 9, 0) = 3
            map(count, 8, 0) = 3
            map(count, 7, 0) = 3
            map(count, 6, 0) = 3
            map(count, 5, 0) = 3
            map(count, 4, 0) = 3
            map(count, 3, 0) = 3
            map(count, 2, 0) = 3
            map(count, 1, 0) = 3
            map(count, 0, 0) = 3

        Next





        'Set Foreground tile values (X,Y,2)
        map(22, 22, 2) = 1
        map(22, 23, 2) = 4
        map(22, 24, 2) = 4
        map(23, 24, 2) = 3
        map(21, 24, 2) = 3
        map(22, 25, 2) = 2
        map(22, 26, 2) = 2
        map(22, 27, 2) = 3
        map(23, 26, 2) = 2
        map(24, 26, 2) = 2
        map(25, 26, 2) = 2
        map(26, 26, 2) = 2
        map(27, 26, 2) = 2
        map(28, 26, 2) = 2
        map(23, 27, 2) = 3
        map(24, 27, 2) = 3
        map(25, 27, 2) = 3
        map(26, 27, 2) = 3
        map(27, 27, 2) = 3
        map(28, 27, 2) = 3
        map(29, 26, 2) = 2
        map(29, 27, 2) = 3
        map(29, 25, 2) = 2
        map(28, 25, 2) = 2
        map(27, 25, 2) = 2
        map(26, 25, 2) = 2
        map(25, 25, 2) = 2
        map(24, 25, 2) = 2
        map(23, 25, 2) = 2
        map(21, 25, 2) = 2 '
        map(21, 26, 2) = 2
        map(21, 27, 2) = 3
        map(20, 27, 2) = 3
        map(30, 27, 2) = 3
        map(48, 50, 2) = 2
        map(49, 50, 2) = 2
        map(45, 21, 2) = 2

        'Glass tiles (24,23) - (29,22)
        For count As Integer = 24 To 29
            map(count, 24, 2) = 3
            map(count, 23, 2) = 2
            map(count, 22, 2) = 2
        Next


        'Glass Area (41,51) - (54,51) 
        For count As Integer = 41 To 54
            map(count, 51, 2) = 2
        Next


        'Glass Tiles (21,29) - (29,27)
        For count As Integer = 28 To 37
            map(21, count, 2) = 2
            map(22, count, 2) = 2
            map(23, count, 2) = 2
            map(24, count, 2) = 2
            map(25, count, 2) = 2
            map(26, count, 2) = 2
            map(27, count, 2) = 2
            map(28, count, 2) = 2
            map(29, count, 2) = 2

        Next

        'Glass Tile Ends (20,38) - (30,38)
        For count As Integer = 20 To 30

            If count <> 25 Then 'Skip (25,38)
                map(count, 38, 2) = 3
            End If

        Next

        'Glass Stairs (25,38) - (25,43)
        For count As Integer = 38 To 43
            map(25, count, 2) = 4
        Next

        'Glas Stairs (25,65) - (25,73)
        For count As Integer = 65 To 73
            map(25, count, 2) = 4
        Next

        'Glass path (43,64) - (50,64) 
        For count As Integer = 43 To 50
            map(count, 64, 2) = 2
        Next


        'Glass Tile Ends (32,37) - (46,37)
        For count As Integer = 32 To 46
            map(count, 37, 2) = 3
        Next

        'Stone Area (51,59) - (61,70) 
        For count As Integer = 51 To 61
            For count2 As Integer = 59 To 70
                map(count, count2, 2) = 6
            Next
        Next

        'Stone area (20,71) - (39,84) 
        For count As Integer = 20 To 39
            For count2 As Integer = 74 To 84
                map(count, count2, 2) = 6
            Next
        Next

        'Glass Tiles (30,23) - (49,21)
        For count As Integer = 30 To 49
            map(count, 23, 2) = 2
            map(count, 22, 2) = 2
        Next

        'Glass path (40,79) - (64,79) 
        For count As Integer = 40 To 64
            map(count, 79, 2) = 2
        Next

        'Glass Tile end (30,24) - (49,24)
        For count As Integer = 30 To 50
            map(count, 24, 2) = 3
        Next
        map(27, 27, 2) = 4

        'Wood Area (20,59) - (42,64)
        For count As Integer = 20 To 42
            For count2 As Integer = 59 To 64
                map(count, count2, 2) = 5
            Next
        Next

        'Wood area (66,85) - (82,69) 
        For count As Integer = 65 To 82
            For count2 As Integer = 69 To 85
                map(count, count2, 2) = 5
            Next
        Next

        'Stairs by Spawn point
        map(27, 24, 2) = 4
        map(26, 24, 2) = 4
        map(26, 27, 2) = 4

        'Stairs by Side path 
        map(39, 24, 1) = 0
        map(39, 24, 2) = 4
        map(39, 25, 2) = 4
        map(39, 26, 2) = 4
        map(39, 27, 2) = 4
        map(46, 21, 2) = 2

        'Stairs from (25,52) - (25,58) 
        For count As Integer = 52 To 58
            map(25, count, 2) = 4
        Next

        'Set Npc tile values (X,Y,3)

        map(28, 30, 3) = 2 'Witch
        map(28, 31, 3) = 3 'Guy in a suit
        map(28, 32, 3) = 4 'White hair guy
        map(33, 29, 3) = 5 'Food Seller 
        map(33, 31, 3) = 5 'potion seller 
        map(33, 33, 3) = 5 'super heal seller 
        map(45, 29, 3) = 7 'escape rope seller 
        map(45, 31, 3) = 7 'Mega heal seller
        map(45, 33, 3) = 7 'healer 
        map(22, 30, 3) = 8 'Pink Witch 
        map(22, 31, 3) = 5 'Red hooded Guy 
        map(22, 32, 3) = 9 'Red Hair guy 
        map(25, 34, 3) = 10 'Vampire
        map(33, 44, 3) = 13 'Angel 
        map(20, 45, 3) = 9  'Red Hair Guy 2
        map(20, 47, 3) = 8  'Witch 2
        map(20, 49, 3) = 8  'Witch 3
        map(40, 45, 3) = 16 'Snow Girl 
        map(40, 47, 3) = 17 'Wise Man lookig left 
        map(40, 49, 3) = 16 'Snow Girl 2
        map(20, 60, 3) = 8 'Pink Witch 3
        map(20, 62, 3) = 18 'Purple Witch 
        map(20, 64, 3) = 19 'White Hair guy 2
        map(29, 61, 3) = 20 'Knight 
        map(36, 61, 3) = 20 'Knight 2
        map(42, 60, 3) = 16 'Snow girl 3
        map(42, 62, 3) = 16 'Snow girl 4
        map(53, 60, 3) = 20 'Knight 3
        map(59, 60, 3) = 20 'Knight 4
        map(52, 67, 3) = 20 'Knight 5
        map(59, 67, 3) = 20 'Knight 6
        map(20, 74, 3) = 19 'White Hair guy 3
        map(20, 76, 3) = 5 'Red Hooded Guy 
        map(20, 78, 3) = 8 'Witch 4
        map(20, 80, 3) = 5 'Red Hooded guy 
        map(20, 84, 3) = 10 'Vampire 2
        map(35, 75, 3) = 20 'Town Guard
        map(29, 75, 3) = 20 'Town guard 2
        map(35, 81, 3) = 20 'Town Guard 3
        map(29, 81, 3) = 13 'Angel 2



        'Set Interact tile values (X,Y,4)
        map(22, 23, 4) = 1 'Introduction
        map(27, 32, 4) = 2 'Battle with Lord Harkon
        map(39, 30, 4) = 3 'Market Sign 
        map(39, 32, 4) = 3 'Market Sign 
        map(38, 31, 4) = 3 'Market Sign 
        map(40, 31, 4) = 3 'Market Sign 
        map(34, 29, 4) = 4 'Food seller 
        map(34, 31, 4) = 5 'Potion seller 
        map(34, 33, 4) = 6 'Super heal seller
        map(44, 29, 4) = 7  'Escape rope seller
        map(44, 31, 4) = 8 'Mega heal 
        map(44, 33, 4) = 9 'Healer 
        map(27, 31, 4) = 10 'Battle with Bishop 
        map(27, 30, 4) = 11 'Battle with Smith 
        map(23, 30, 4) = 12 'Battle with The pink curse
        map(23, 32, 4) = 13 'Battle With Wise Punk 
        map(23, 31, 4) = 14 'Battle with the Wise Monk 
        map(25, 33, 4) = 15 'Battle with Count Doom 
        map(33, 45, 4) = 16 'Battle With Hunting Hawk
        map(39, 45, 4) = 17 'Battle With Snow Girl 
        map(39, 47, 4) = 18 'Battle with the Wise One 
        map(39, 49, 4) = 17 'Battle With snow Girl 2
        map(21, 45, 4) = 13 'Battle Wise Punk 2
        map(21, 47, 4) = 12 'Battle With the pink Curse
        map(21, 49, 4) = 12 'Battle With the Pink Curse 2
        map(48, 51, 4) = 19 'Dungeon Sign 
        map(41, 60, 4) = 17 'Battle With Snow Girl 3
        map(41, 62, 4) = 17 'Battle With Snow Girl 4
        map(21, 60, 4) = 12 'Battle with The pink curse 2
        map(21, 62, 4) = 20 'Battle with The purple curse
        map(21, 64, 4) = 21 'Battle with the reactor 
        map(29, 62, 4) = 22 'Battle with the knight 
        map(36, 62, 4) = 22 'Battle with the knight 2
        map(53, 61, 4) = 23 'Battle with the Town Guard 1
        map(59, 61, 4) = 23 'Battle with the Town Guard 2
        map(52, 68, 4) = 23 'Battle with the Town Guard 3
        map(59, 68, 4) = 23 'Battle with the Town Guard 4
        map(35, 76, 4) = 23 'Battle with the Town Guard 5
        map(29, 76, 4) = 23 'Battle with theTown guard 6
        map(35, 82, 4) = 23 'Battle with the Town Guard 7
        map(29, 82, 4) = 24 'Battle with Running Hawk 
        map(21, 78, 4) = 12 'Battle with Witch 4
        map(21, 76, 4) = 14 'Battle with the Wise Monk 2
        map(21, 80, 4) = 14 'Battle with the Wise Monk 3
        map(20, 83, 4) = 25 'Battle with count maul 
        map(21, 74, 4) = 21 'Battle with the reactor 2
        map(73, 80, 4) = 26 'Castle Sign 
        map(74, 79, 4) = 27 'Enter Castle of the lord
        map(49, 50, 4) = 30 'Enter Dungeon of the Master
        map(45, 22, 4) = 33 'Enter the Leaders House
        map(46, 23, 4) = 32 'The leaders sign 

        'Set Foreground 2 tile values (X,Y,5)

        'Arc 1
        map(25, 28, 6) = 5
        map(25, 27, 6) = 4
        map(25, 26, 6) = 2
        map(26, 26, 6) = 1
        map(27, 26, 6) = 3
        map(27, 27, 6) = 6
        map(27, 28, 6) = 7
        map(26, 27, 6) = 8

        'Arc 2
        map(25, 25, 6) = 5
        map(25, 24, 6) = 4
        map(25, 23, 6) = 2
        map(26, 23, 6) = 1
        map(27, 23, 6) = 3
        map(27, 24, 6) = 6
        map(27, 25, 6) = 7
        map(26, 24, 6) = 8

        'Arc 3
        map(24, 39, 6) = 5
        map(24, 38, 6) = 4
        map(24, 37, 6) = 2
        map(25, 37, 6) = 1
        map(26, 37, 6) = 3
        map(26, 38, 6) = 6
        map(26, 39, 6) = 7
        map(25, 38, 6) = 8

        'Arc 4
        map(24, 44, 6) = 5
        map(24, 43, 6) = 4
        map(24, 42, 6) = 2
        map(25, 42, 6) = 1
        map(26, 42, 6) = 3
        map(26, 43, 6) = 6
        map(26, 44, 6) = 7
        map(25, 43, 6) = 8

        'Arc 5
        map(24, 53, 6) = 5
        map(24, 52, 6) = 4
        map(24, 51, 6) = 2
        map(25, 51, 6) = 1
        map(26, 51, 6) = 3
        map(26, 52, 6) = 6
        map(26, 53, 6) = 7
        map(25, 52, 6) = 8

        'Arc 6
        map(24, 59, 6) = 5
        map(24, 58, 6) = 4
        map(24, 57, 6) = 2
        map(25, 57, 6) = 1
        map(26, 57, 6) = 3
        map(26, 58, 6) = 6
        map(26, 59, 6) = 7
        map(25, 58, 6) = 8

        'Arc 7
        map(24, 66, 6) = 5
        map(24, 65, 6) = 4
        map(24, 64, 6) = 2
        map(25, 64, 6) = 1
        map(26, 64, 6) = 3
        map(26, 65, 6) = 6
        map(26, 66, 6) = 7
        map(25, 65, 6) = 8

        'Arc 8
        map(24, 74, 6) = 5
        map(24, 73, 6) = 4
        map(24, 72, 6) = 2
        map(25, 72, 6) = 1
        map(26, 72, 6) = 3
        map(26, 73, 6) = 6
        map(26, 74, 6) = 7
        map(25, 73, 6) = 8

        'Statue 1 
        map(32, 43, 6) = 10
        map(32, 44, 6) = 11


        'Statue 2
        map(34, 43, 6) = 10
        map(34, 44, 6) = 11

        'Market Sign
        map(39, 31, 6) = 9

        'Dungeon Sign 
        map(48, 50, 6) = 9

        'Castle Sign 
        map(73, 79, 6) = 9

        'The Leaders Sign 
        map(46, 22, 6) = 9


        'Set Building Values (X,Y,7)
        map(43, 37, 7) = 1 'Dungeon
        map(30, 56, 7) = 2 'Shrine
        map(53, 56, 7) = 3 'Large House
        map(53, 65, 7) = 4 'Medium Sized House
        map(29, 72, 7) = 5 'Small House
        map(29, 78, 7) = 5 'Small House 2
        map(68, 66, 7) = 1 'Dungeon 2
        map(43, 18, 7) = 5 'Small House 3




    End Sub

    'Update Collision Values to amke sure object maintain either a solid or passable value
    Public Sub Collisions(ByRef map As Array)

        'Set Collisions (X,Y,1) only if current map is 1 

        If modSaveData.map = 1 Then 'Map 1

            'Dungeon 1
            For count As Integer = 41 To 51
                map(count, 50, 1) = 1
            Next

            'Dungeon Path 1
            map(48, 50, 1) = 0
            map(49, 50, 1) = 0
            map(48, 49, 1) = 1
            map(49, 49, 1) = 1
            map(48, 50, 1) = 1
            map(45, 21, 1) = 1


            'Large House
            For count As Integer = 54 To 58
                map(count, 59, 1) = 1
                map(count, 60, 1) = 1
            Next

            'medium sized house
            For count As Integer = 53 To 58
                For count2 As Integer = 65 To 67
                    map(count, count2, 1) = 1
                Next
            Next

            'Shrine 
            For count As Integer = 30 To 35
                For count2 As Integer = 59 To 61
                    map(count, count2, 1) = 1
                Next
            Next

            'Small House
            For count As Integer = 30 To 34
                For count2 As Integer = 74 To 75
                    map(count, count2, 1) = 1
                Next
            Next

            'Small House 2
            For count As Integer = 30 To 34
                For count2 As Integer = 79 To 81
                    map(count, count2, 1) = 1
                Next
            Next

            'Glass path (40,79) - (64,79) 
            For count As Integer = 40 To 64
                map(count, 79, 1) = 0
            Next

            'Castle 
            For count As Integer = 68 To 80
                For count2 As Integer = 72 To 79
                    map(count, count2, 1) = 1
                Next
            Next
            map(74, 79, 1) = 0


        End If



    End Sub


End Module
